<div><div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p class="eyebrow mb-2 text-teal-600">Administrasi pasien</p><h1 class="page-title">Data pasien</h1><p class="subtitle">Satu identitas pasien untuk seluruh pelayanan klinik.</p></div>
@can('patients.create')<button class="btn" wire:click="create"><x-ui.icon name="plus"/>Pasien baru</button>
@endcan</div><x-ui.feedback/>
<section class="card"><div class="card-header"><span class="text-sm font-semibold">Direktori pasien <span class="ml-2 rounded bg-slate-100 px-2 py-1 text-xs text-slate-500">{{ $rows->total() }}</span></span><div class="relative w-full max-w-sm"><x-ui.icon name="search" class="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input class="field pl-9" wire:model.live.debounce.350ms="search" placeholder="Cari nama, nomor RM, NIK, telepon…" aria-label="Cari pasien"></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Pasien</th><th>Nomor RM</th><th>Lahir / usia</th><th>Telepon</th><th>Penjamin</th><th></th></tr></thead><tbody>
@forelse($rows as $patient)<tr><td><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-teal-50 font-bold text-teal-700">{{ substr($patient->name,0,1) }}</span><div class="font-semibold text-slate-800">{{ $patient->name }}<span class="mt-1 block text-[10px] font-normal text-slate-400">{{ $patient->sex==='L'?'Laki-laki':'Perempuan' }} · {{ $patient->active?'Aktif':'Nonaktif' }}</span></div></div></td><td class="font-mono text-xs">{{ $patient->medical_number }}</td><td>{{ $patient->birth_date->format('d M Y') }}<span class="mt-1 block text-[10px] text-slate-400">{{ $patient->birth_date->age }} tahun</span></td><td>{{ $patient->phone?:'—' }}</td><td>{{ $patient->payer }}</td><td>
@can('patients.update')<button class="link text-xs" wire:click="edit({{ $patient->id }})">Edit pasien</button>
@endcan</td></tr>
@empty<tr><td colspan="6"><x-ui.empty>Pasien belum ditemukan. Daftarkan pasien baru untuk memulai.</x-ui.empty></td></tr>
@endforelse</tbody></table></div><div class="p-4">{{ $rows->links() }}</div></section>
@if($showForm)<x-ui.modal :title="$editing?'Edit pasien':'Daftarkan pasien baru'"><x-ui.feedback/>
@if($duplicates->count())<div class="mb-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Kemungkinan pasien sudah terdaftar: 
@foreach($duplicates as $duplicate)<p class="mt-1">{{ $duplicate->name }} · {{ $duplicate->medical_number }}</p>
@endforeach</div>
@endif<form wire:submit="save"><div class="form-grid"><label><span class="label">Nama lengkap *</span><input class="field" wire:model.live.debounce.500ms="form.name"></label><x-ui.field label="NIK (opsional)" model="form.nik" maxlength="16"/><x-ui.field label="Tempat lahir" model="form.birth_place"/><x-ui.field label="Tanggal lahir *" model="form.birth_date" type="date"/><label><span class="label">Jenis kelamin</span><select class="field" wire:model="form.sex"><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label><x-ui.field label="Telepon" model="form.phone"/><x-ui.field label="Alamat" model="form.address"/><label><span class="label">Golongan darah</span><select class="field" wire:model="form.blood_type"><option value="">Belum diketahui</option>
@foreach(['A','B','AB','O','-'] as $blood)<option>{{ $blood }}</option>
@endforeach</select></label><x-ui.field label="Kontak darurat" model="form.emergency_contact"/><x-ui.field label="Penjamin" model="form.payer"/><label class="flex items-center gap-2 text-sm"><input wire:model="form.active" type="checkbox">Pasien aktif</label></div><div class="mt-6 flex justify-end"><button class="btn" wire:loading.attr="disabled">Simpan pasien</button></div></form></x-ui.modal>
@endif</div>