<div wire:poll.30s>
<div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p class="eyebrow mb-2 text-teal-600">Clinical operations / overview</p><h1 class="page-title">Pusat Kendali SIM Klinik Enterprise</h1><p class="subtitle">Sistem Informasi Manajemen Klinik, Apotek, dan Pelayanan Medis Terintegrasi</p></div><span class="flex items-center gap-2 rounded-full border border-teal-200 bg-teal-50 px-3 py-1.5 text-[11px] font-semibold text-teal-700"><span class="h-1.5 w-1.5 rounded-full bg-teal-500"></span>Workspace aktif</span></div>
<section class="relative mb-6 overflow-hidden rounded-2xl bg-[#123d47] px-7 py-7 text-white"><div class="absolute -right-12 -top-24 h-80 w-80 rounded-full border-[45px] border-white/[.03]"></div><div class="absolute right-40 top-12 h-44 w-44 rounded-full border-[25px] border-white/[.03]"></div><div class="relative flex flex-wrap items-center justify-between gap-6"><div><p class="mb-2 text-[10px] font-semibold uppercase tracking-[.22em] text-teal-300">Selamat datang, {{ explode(' ',auth()->user()->name)[0] }}</p><h2 class="text-2xl font-semibold tracking-tight text-white">Clinical Operations Workspace</h2><p class="mt-2 max-w-xl text-sm leading-6 text-teal-100/60">Pantau alur pasien, pelayanan medis, resep, dan operasional klinik dalam satu ruang kerja.</p>
@can('visits.register')<a href="{{ route('visits') }}" wire:navigate class="mt-5 inline-flex items-center gap-2 rounded-lg bg-teal-400 px-4 py-2.5 text-xs font-bold text-teal-950"><x-ui.icon name="plus" class="h-4 w-4"/>Daftarkan kunjungan<x-ui.icon name="arrow" class="ml-3 h-4 w-4"/></a>
@endcan</div><div class="hidden border-l border-white/10 pl-8 text-right md:block"><p class="text-[10px] uppercase tracking-widest text-teal-100/50">Rata-rata waktu tunggu</p><p class="mt-2 text-4xl font-light">{{ $average }} <span class="text-base text-teal-200/60">menit</span></p><p class="mt-2 text-xs text-teal-100/40">Registrasi → pemeriksaan dokter hari ini</p></div></div></section>
<div class="mb-6 grid grid-cols-2 gap-4 xl:grid-cols-4">
@foreach([['Pasien hari ini',$metrics['today'],'users','Total kunjungan terdaftar'],['Antrean menunggu',$metrics['waiting'],'clock',$metrics['consulting'].' pasien sedang diperiksa'],['Resep menunggu',$metrics['pharmacy'],'pill','Verifikasi & penyerahan obat'],[$metrics['revenue']!==null?'Pendapatan hari ini':'Kunjungan selesai',$metrics['revenue']!==null?\App\Support\Money::format($metrics['revenue']):$metrics['completed'],'wallet',$metrics['revenue']!==null?'Penerimaan setelah reversal':'Pelayanan & pembayaran selesai']] as [$label,$value,$icon,$detail])<div class="card p-5"><div class="flex items-center justify-between"><span class="text-xs font-medium text-slate-500">{{ $label }}</span><span class="rounded-lg bg-teal-50 p-2 text-teal-600"><x-ui.icon :name="$icon" class="h-4 w-4"/></span></div><p class="mt-3 text-2xl font-bold tracking-tight text-slate-900">{{ $value }}</p><p class="mt-2 text-[11px] text-slate-400">{{ $detail }}</p></div>
@endforeach</div>
<div class="mb-6 grid gap-6 xl:grid-cols-3"><section class="card xl:col-span-2"><div class="card-header"><div><h2 class="text-sm font-bold">Tren kunjungan pasien</h2><p class="mt-1 text-[11px] text-slate-400">Aktivitas pelayanan selama 7 hari terakhir</p></div><span class="rounded-md border border-slate-200 px-3 py-1.5 text-[11px] text-slate-500">7 hari terakhir</span></div><div class="p-6"><div class="mb-5 flex items-baseline gap-2"><span class="text-3xl font-bold text-slate-900">{{ collect($series)->sum('count') }}</span><span class="text-xs text-slate-400">total kunjungan</span></div><div class="relative flex h-40 items-end justify-around gap-3 border-b border-slate-100" role="img" aria-label="Grafik kunjungan tujuh hari">
@foreach($series as $point)<div class="group flex h-full flex-1 flex-col justify-end items-center"><span class="mb-1 text-[10px] text-slate-500">{{ $point['count'] }}</span><div class="w-full max-w-10 rounded-t-md bg-teal-500/80 transition hover:bg-teal-600" style="height:{{ max(3,$point['count']/max(1,collect($series)->max('count'))*110) }}px"></div></div>
@endforeach</div><div class="mt-3 flex justify-around">
@foreach($series as $point)<span class="flex-1 text-center text-[10px] text-slate-400">{{ $point['label'] }}</span>
@endforeach</div></div></section>
<section class="card"><div class="card-header"><h2 class="text-sm font-bold">Jadwal pelayanan</h2><span class="text-[10px] text-teal-600">HARI INI</span></div><div class="divide-y divide-slate-100">
@forelse($schedules as $schedule)<div class="flex items-center gap-3 px-5 py-4"><span class="rounded-full bg-slate-100 p-2.5 text-slate-500"><x-ui.icon name="pulse" class="h-4 w-4"/></span><div class="flex-1"><p class="text-xs font-semibold text-slate-800">{{ $schedule->staff->name }}</p><p class="mt-1 text-[11px] text-slate-400">{{ $schedule->polyclinic->name }} · {{ substr($schedule->starts_at,0,5) }}–{{ substr($schedule->ends_at,0,5) }}</p></div><span class="h-2 w-2 rounded-full bg-teal-400"></span></div>
@empty<x-ui.empty>Tidak ada jadwal hari ini.</x-ui.empty>
@endforelse</div><div class="m-4 rounded-lg bg-slate-50 p-3 text-[11px] leading-relaxed text-slate-500">Pelayanan terhubung dari pendaftaran, pemeriksaan, hingga kasir.</div></section></div>
@can('visits.view')<section class="card mb-6"><div class="card-header"><div><h2 class="text-sm font-bold">Kunjungan terbaru</h2><p class="mt-1 text-[11px] text-slate-400">Pantau perjalanan pasien hari ini</p></div><a href="{{ route('visits') }}" wire:navigate class="link text-xs">Lihat semua →</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Pasien</th><th>Poli</th><th>Antrean</th><th>Status pelayanan</th><th></th></tr></thead><tbody>
@forelse($visits as $visit)<tr><td><p class="font-semibold text-slate-800">{{ $visit->patient->name }}</p><p class="mt-1 text-[11px] text-slate-400">{{ $visit->patient->medical_number }}</p></td><td>{{ $visit->polyclinic->name }}</td><td class="font-mono text-teal-700">{{ str_pad($visit->queue->number,3,'0',STR_PAD_LEFT) }}</td><td><x-ui.badge :status="$visit->status"/></td><td><a href="{{ route('visits.show',$visit) }}" wire:navigate class="link text-xs">Buka →</a></td></tr>
@empty<tr><td colspan="5"><x-ui.empty>Belum ada kunjungan hari ini.</x-ui.empty></td></tr>
@endforelse</tbody></table></div></section>
@endcan
<div class="grid gap-6 lg:grid-cols-2">
@if(auth()->user()->can('inventory.view') || auth()->user()->can('reports.view'))<section class="card"><div class="card-header"><h2 class="text-sm font-bold">Perhatian persediaan</h2><span class="rounded-md bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-700">{{ $lowStock->count()+$expiry->count() }} PERINGATAN</span></div><div class="divide-y divide-slate-100">
@foreach($lowStock as $m)<div class="flex justify-between px-5 py-3 text-xs"><span>{{ $m->name }}<span class="mt-1 block text-[10px] text-slate-400">Di bawah batas minimum {{ $m->minimum_stock }}</span></span><span class="font-semibold text-amber-600">{{ $m->available??0 }} tersisa</span></div>
@endforeach 
@foreach($expiry as $batch)<div class="flex justify-between px-5 py-3 text-xs"><span>{{ $batch->medicine->name }}<span class="mt-1 block text-[10px] text-slate-400">Batch {{ $batch->batch_number }}</span></span><span class="text-red-500">{{ $batch->expires_on->format('d M Y') }}</span></div>
@endforeach 
@if(!$lowStock->count()&&!$expiry->count())<x-ui.empty>Persediaan dalam kondisi baik.</x-ui.empty>
@endif</div></section>
@endif
@can('audit.view')<section class="card"><div class="card-header"><h2 class="text-sm font-bold">Aktivitas terbaru</h2><a href="{{ route('audit') }}" wire:navigate class="link text-xs">Audit log →</a></div><div class="px-5">
@foreach($activity as $item)<div class="flex gap-3 border-b border-slate-50 py-3"><span class="mt-1.5 h-2 w-2 rounded-full bg-teal-400"></span><div class="flex-1"><p class="text-xs font-medium text-slate-700">{{ $item->action }}</p><p class="mt-1 text-[10px] text-slate-400">{{ $item->actor?->name }} · {{ $item->subject_type }} #{{ $item->subject_id }}</p></div><span class="text-[10px] text-slate-400">{{ $item->created_at->format('H:i') }}</span></div>
@endforeach</div></section>
@endcan</div></div>
